appearance:
  theme_day: minimal
  # theme_night: minimal
  font: minimal
  font_size: M

# SEO

marketing:
  seo:
    site_type: Person
    local_business_type: ''
    org_name: ''
    description: 'GLADIA Research Group, Sapienza University of Rome.'
    twitter: ''
  analytics:
    google_analytics: 'G-N916QE5DYG'
    baidu_tongji: ''
  verification:
    google: ''
    baidu: ''

# Site header

header:
  navbar:
    enable: true
    align: l
    show_logo: true
    show_language: false
    show_day_night: false
    show_search: true
    highlight_active_link: true

# Site footer

footer:
  copyright:
    notice: 'Emanuele Rodolà © {year} -- Made and maintained by Donato Crisostomi.'
    license:
      enable: false
      allow_derivatives: false
      share_alike: false
      allow_commercial: false

# Localization

locale:
  date_format: 'Jan 2, 2006'
  time_format: '3:04 PM'
  address_format: en-us

# Site features

features:
  syntax_highlighter:
    theme_light: github-light
    theme_dark: dracula
  math:
    enable: false
  privacy_pack:
    enable: true
  repository:
    url: 'https://github.com/<username>/<repository>'
    content_dir: content
    branch: main
  avatar:
    gravatar: false
    shape: circle
  comment:
    provider: ''
    disqus:
      shortname: ''
      show_count: true
    commento:
      url: ''
    giscus:
      repo: ''
      repo_id: ''
      category: ''
      category_id: ''
  search:
    provider: wowchemy
    algolia:
      app_id: ''
      api_key: ''
      index_name: ''
      show_logo: false
  map:
    provider: 'mapbox'
    api_key: ''
    zoom: 0

# Extensions

extensions:
  cms:
    branch: main
    local_backend: false
  academicons:
    enable: true

# Security

security:
  # Allow frame for embedding speaker notes in slides
  allow_frame: true
